[package]
name = "svf-hack"
version = "0.1.0"
authors = ["Jake Howard <jake@jakehowrd.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
csv = "1.1.3"
